name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Boost Dependency
      run: brew install boost
    - name: Configure
      env:
        CC: gcc-8
        CXX: g++-8
      run: mkdir build && cd build && cmake ..
    - name: Build
      run: cmake --build build --config Release --target install
    - name: Run unit tests
      run: cd bin && ./unit_tests && mv overwatch_* overwatch
    - uses: actions/upload-artifact@v2
      with:
        name: overwatch_LINUX
        path: bin/overwatch

  build-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      env:
        BOOST_ROOT: $ENV{BOOST_ROOT_1_72_0}
      run: mkdir build && cd build && cmake ..
    - name: Build
      run: cmake --build build --config Release --target install
    - name: Run unit tests
      run: cd bin && ./unit_tests && mv overwatch_* overwatch
    - uses: actions/upload-artifact@v2
      with:
        name: overwatch_WINDOWS
        path: bin/overwatch
