name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: brew install boost
    - name: Configure
      env:
        CC: gcc-8
        CXX: g++-8
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE:STRING=MinSizeRel
    - name: Build
      run: cmake --build build --config Release --target install && mv bin/overwatch-MinSizeRel bin/overwatch
    - name: Run unit tests
      run: cd bin && ./unit_tests
    - uses: actions/upload-artifact@v2
      with:
        name: overwatch_LINUX
        path: bin/overwatch

  build-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE:STRING=MinSizeRel
    - name: Build
      run: cmake --build build --config Release --target install && mv bin/overwatch-MinSizeRel bin/overwatch
    - name: Run unit tests
      run: cd bin && ./unit_tests
    - uses: actions/upload-artifact@v2
      with:
        name: overwatch_WINDOWS
        path: bin/overwatch
