name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install boost dependency
      run: brew install boost@1.72
    - name: configure
      env:
        CC: gcc-8
        CXX: g++-8
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Release --target install
    - name: test
      run: cd bin && ls

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Release --target install
    - name: test
      run: cd bin && ./unit_tests-Release
